//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesAction
    {
        public int RoleId { get; set; }
        public string Action { get; set; }
    }
}
