//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1
{
    using System;
    using System.Collections.Generic;
    [TypeLite.TsClass]
    public partial class Ivhunim
    {
        public int Id { get; set; }
        public Nullable<bool> ReadyToBeSent { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Institue { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public string Grade { get; set; }
        public string School { get; set; }
        public string Address { get; set; }
        public string ParentName { get; set; }
        public string ParentPhone { get; set; }
        public string ParentEmail { get; set; }
        public string Reason { get; set; }
        public string WhoSent { get; set; }
        public string Background { get; set; }
        public string OverallImpression { get; set; }
        public Nullable<bool> IsToniEnabled { get; set; }
        public Nullable<int> ToniRightAnswers { get; set; }
        public Nullable<bool> IsIptaEnabled { get; set; }
        public Nullable<int> IptaRightAnswers { get; set; }
        public Nullable<bool> IsGlanzEnabled { get; set; }
        public Nullable<int> GlanzNigudiyut { get; set; }
        public Nullable<int> GlanzNirdafot { get; set; }
        public Nullable<int> GlanzMahutiyot { get; set; }
        public Nullable<int> GlanzHagdara { get; set; }
        public Nullable<int> GlanzMiyun { get; set; }
        public Nullable<int> GlanzSivug { get; set; }
        public Nullable<int> GlanzPitgamim { get; set; }
        public Nullable<int> GlanzAnalogya { get; set; }
        public Nullable<int> GlanzHasakatMaskanot { get; set; }
        public string GlanzSikum { get; set; }
        public string YedaOrtography { get; set; }
        public Nullable<int> MilimBeheksherDiyuk { get; set; }
        public Nullable<int> MilimBodedotDiyuk { get; set; }
        public Nullable<int> MilotTefelDiyuk { get; set; }
        public Nullable<int> ItzurimVetnuotDiyuk { get; set; }
        public Nullable<int> MilimBeheksherKetzev { get; set; }
        public Nullable<int> MilimBodedotKetzev { get; set; }
        public Nullable<int> MilotTefelKetzev { get; set; }
        public Nullable<int> ItzurimVetnuotKetzev { get; set; }
        public string SikumTahaliheyKria { get; set; }
        public Nullable<bool> IsHavanatHanikraEnabled { get; set; }
        public string SikumHavanatHanikra { get; set; }
        public Nullable<bool> IsHavanatHanishmaEnabled { get; set; }
        public string SikumHavanatHanishma { get; set; }
        public Nullable<bool> IsKtivaEnabled { get; set; }
        public string Ktav { get; set; }
        public string Ktiv { get; set; }
        public string TshuvotLesheelotBezikaLetext { get; set; }
        public string HabaaBektav { get; set; }
        public Nullable<bool> IsHabaBealpeEnabled { get; set; }
        public string SikumHabaBealpe { get; set; }
        public Nullable<bool> IsEranutMetaLeshonitEnabled { get; set; }
        public string MudautFonologit { get; set; }
        public string Ran { get; set; }
        public string ShetefMiluli { get; set; }
        public string EranutMorfoTahbirit { get; set; }
        public string EranutTahbirit { get; set; }
        public Nullable<bool> IsZikaronmMiluliEnabled { get; set; }
        public string Kidron { get; set; }
        public string Rey { get; set; }
        public string Rey1 { get; set; }
        public string Rey2 { get; set; }
        public string Rey3 { get; set; }
        public string Rey4 { get; set; }
        public string Rey5 { get; set; }
        public string Rey6 { get; set; }
        public string Rey7 { get; set; }
        public string Rey8 { get; set; }
        public string Rey9 { get; set; }
        public string ZikaronAvoda { get; set; }
        public string TifkudimNuhuliyim { get; set; }
        public string ZikaronMiyadiShlifa { get; set; }
        public string ZikaronMoshheShlifa { get; set; }
        public string KidudVehasmala { get; set; }
        public string KimGame { get; set; }
        public string KeshevHazuti { get; set; }
        public string KetzevYahalom { get; set; }
        public string DiyukYahalom { get; set; }
        public string Ketzev592 { get; set; }
        public string Diyuk592 { get; set; }
        public string Sikum { get; set; }
        public string Hamlazot { get; set; }
        public string HatamotLedarkayHibahanut { get; set; }
        public string Tz { get; set; }
    }
}
