//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace a1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User(User ivhunToCopy)
        {
            this.Email = ivhunToCopy.Email;
            this.FirstName = ivhunToCopy.FirstName;
            this.LastName = ivhunToCopy.LastName;
        }

        public User()
        {

        }

        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
    }
}
